### ISSUE TITLE
iojs 3.0 support

### ISSUE THREAD

**Issue by CollinEstes** [strongloop/strong-oracle#47]
More of an fyi, there is an error when installing strong-oracle with iojs 3.0.0:

```
In file included from ../src/connection.h:6:0,
                 from ../src/connection.cpp:2:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../node_modules/nan/nan.h:780:3: warning: control reaches end of non-void function [-Wreturn-type]


oracle_bindings.target.mk:95: recipe for target 'Release/obj.target/oracle_bindings/src/connection.o' failed

make: *** [Release/obj.target/oracle_bindings/src/connection.o] Error 1
make: Leaving directory '/src/node_modules/strong-oracle/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-61-generic
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /src/node_modules/strong-oracle
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm info strong-oracle@1.6.5 Failed to exec install script
npm ERR! Linux 3.13.0-61-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "strong-oracle"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
```

To easily reproduce feel free to use the Docker image I've created to setup a node/strong-oracle ready container: 

https://github.com/CollinEstes/docker-node-oracle.
https://hub.docker.com/r/collinestes/docker-node-oracle/

(Also this Docker image might be useful to people wanting to use strong-oracle and struggle with the installation/setup, so feel free to link to it in the doc if interested)

**Comment by raymondfeng** [comment]
Dup of #50
