### ISSUE TITLE
Node v4 support

### ISSUE THREAD

**Issue by lebolo** [strongloop/strong-oracle#50]
Will there be plans to support node v4? This may be related to #47.

```
-bash-4.2$ npm install strong-oracle
/
> strong-oracle@1.6.5 install /srv/wart/wart/node_modules/strong-oracle
> node-gyp rebuild

make: Entering directory `/srv/wart/wart/node_modules/strong-oracle/build'
  CXX(target) Release/obj.target/oracle_bindings/src/connection.o
In file included from ../src/connection.h:6:0,
                 from ../src/connection.cpp:2:
../node_modules/nan/nan.h:324:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:319:17: error: ‘template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)’ previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../node_modules/nan/nan.h:344:27: error: redefinition of ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)’
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../node_modules/nan/nan.h:334:27: error: ‘template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)’ previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../node_modules/nan/nan.h:757:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:757:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:761:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:761:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:768:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:768:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/connection.h:6,
                 from ../src/connection.cpp:2:
/home/hbi91877/.node-gyp/4.0.0/src/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/hbi91877/.node-gyp/4.0.0/src/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/home/hbi91877/.node-gyp/4.0.0/src/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/hbi91877/.node-gyp/4.0.0/src/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/connection.h:6:0,
                 from ../src/connection.cpp:2:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:772:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:779:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/connection.cpp: In static member function ‘static void ConnectionPool::EIO_AfterClose(uv_work_t*)’:
../src/connection.cpp:151:34: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/hbi91877/.node-gyp/4.0.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(tryCatch);
                                  ^
../src/connection.cpp: In static member function ‘static void ConnectionPool::EIO_AfterGetConnection(uv_work_t*)’:
../src/connection.cpp:263:34: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/hbi91877/.node-gyp/4.0.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(tryCatch);
                                  ^
../src/connection.cpp: In static member function ‘static void Connection::EIO_AfterCall(uv_work_t*)’:
../src/connection.cpp:803:34: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/hbi91877/.node-gyp/4.0.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(tryCatch);
                                  ^
../src/connection.cpp: In static member function ‘static void Connection::EIO_AfterClose(uv_work_t*)’:
../src/connection.cpp:873:34: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/hbi91877/.node-gyp/4.0.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(tryCatch);
                                  ^
In file included from ../src/connection.h:6:0,
                 from ../src/connection.cpp:2:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:780:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
make: *** [Release/obj.target/oracle_bindings/src/connection.o] Error 1
make: Leaving directory `/srv/wart/wart/node_modules/strong-oracle/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/srv/wart/node-v4.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-229.11.1.el7.x86_64
gyp ERR! command "/srv/wart/node-v4.0.0-linux-x64/bin/node" "/srv/wart/node-v4.0.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/wart/wart/node_modules/strong-oracle
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Linux 3.10.0-229.11.1.el7.x86_64
npm ERR! argv "/srv/wart/node-v4.0.0-linux-x64/bin/node" "/srv/wart/node/bin/npm" "install" "strong-oracle"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! strong-oracle@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strong-oracle@1.6.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the strong-oracle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls strong-oracle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/wart/wart/npm-debug.log
```

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strong-oracle/pull/51

**Comment by CollinEstes** [comment]
Question on this:  I see #51 has been merged into master so should this have fixed the failing NPM install of strong-oracle when running with node 4?  Since this is still open I'm guessing this is still an open issue.

**Comment by lebolo** [comment]
I run node v5.1.0 (npm 3.4.1) and strong-oracle 1.7.0 with no problems, so if no one else responds I'll go ahead and close this out tomorrow.

**Comment by CollinEstes** [comment]
Strange I just cleared everything and did another npm install strong-oracle running node 4.2.3 and it works now for me, could have sworn just a minute ago I was having issues.  

O well.

**Comment by lebolo** [comment]
:) in that case, I'll go ahead and close
