### ISSUE TITLE
SIGSEGV on Ubuntu 15.10

### ISSUE THREAD

**Issue by ryanjgill** [strongloop/strong-oracle#59]
I'm using the instant client 12 and get the following stack trace when trying to perform a query:  
``` 
PID 15778 received SIGSEGV for address: 0x30f7000
/home/ryan/Projects/mdt_oracle/node_modules/strong-oracle/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x185c)[0x7fc47e1db85c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10d10)[0x7fc4807bcd10]
/opt/oracle/instantclient/libocci.so.12.1(__intel_ssse3_rep_memcpy+0x148)[0x7fc47dd0b288]
/opt/oracle/instantclient/libocci.so.12.1(_intel_fast_memcpy.P+0x6)[0x7fc47dd05c36]
/opt/oracle/instantclient/libclntsh.so.12.1(kpuspcreate+0x520)[0x7fc46e3f40a0]
/opt/oracle/instantclient/libclntsh.so.12.1(OCISessionPoolCreate+0x1ad)[0x7fc46e255f5d]
/opt/oracle/instantclient/libocci.so.12.1(_ZN6oracle4occi27StatelessConnectionPoolImpl10initialiseEPNS0_15EnvironmentImplEPvjS4_jS4_jjjjNS0_23StatelessConnectionPool8PoolTypeE+0x181)[0x7fc47dd3bdd1]
/opt/oracle/instantclient/libocci.so.12.1(_ZN6oracle4occi27StatelessConnectionPoolImplC1EPNS0_15EnvironmentImplERKSsS5_S5_jjjNS0_23StatelessConnectionPool8PoolTypeE+0xd5)[0x7fc47dd390b5]
/opt/oracle/instantclient/libocci.so.12.1(_ZN6oracle4occi15EnvironmentImpl29createStatelessConnectionPoolERKSsS3_S3_jjjNS0_23StatelessConnectionPool8PoolTypeE+0xa1)[0x7fc47dd136c1]
/home/ryan/Projects/mdt_oracle/node_modules/strong-oracle/build/Release/oracle_bindings.node(_ZN12OracleClient24CreateConnectionPoolSyncERKN3Nan20FunctionCallbackInfoIN2v85ValueEEE+0x6ac)[0x7fc47dfce8ec]
/home/ryan/Projects/mdt_oracle/node_modules/strong-oracle/build/Release/oracle_bindings.node(+0x14f85)[0x7fc47dfc9f85]
node(_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+0xaa)[0x900cfa]
node[0x92d227]
node[0x92d6bd]
[0x31cb2750963b]
```

I'm on Ubuntu 15.10 and Node 4.2.4

Any ideas what could be causing this issue?

**Comment by ryanjgill** [comment]
I ended up reinstalling Ubuntu 14.04 LTS and the driver is working great.

**Comment by peleshenko** [comment]
I have same issue. Do you think it is a good idea to close issuse just because you can't reproduce it on 14.04 LTS?

**Comment by stiXits** [comment]
I'm struggling for a while with a very similar issue when using the oracle instant client.
The program has no connection to strongloop but this error seems so rare I can barely find any information on the nets.

When I try to open a connection with the connectionpool (stateless or not doesn't matter), I recieve the following error (gdb backtrace) on ubuntu 16.04 LTS and Arch Linux:

#0  0x00007ffff7b2de03 in __intel_ssse3_rep_memcpy () from /usr/lib/oracle/12.1/client64/lib/libocci.so.12.1
#1  0x00007ffff7b27c36 in _intel_fast_memcpy.P () from /usr/lib/oracle/12.1/client64/lib/libocci.so.12.1
#2  0x00007ffff5e8d69a in kpuspcreate () from /usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1
#3  0x00007ffff5ceef5d in OCISessionPoolCreate () from /usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1
#4  0x00007ffff7b5ddd1 in oracle::occi::StatelessConnectionPoolImpl::initialise(oracle::occi::EnvironmentImpl*, void*, unsigned int, void*, unsigned int, void*, unsigned int, unsigned int, unsigned int, unsigned int, oracle::occi::StatelessConnectionPool::PoolType) () from /usr/lib/oracle/12.1/client64/lib/libocci.so.12.1
#5  0x00007ffff7b5b0b5 in oracle::occi::StatelessConnectionPoolImpl::StatelessConnectionPoolImpl(oracle::occi::EnvironmentImpl*, std::string const&, std::string const&, std::string const&, unsigned int, unsigned int, unsigned int, oracle::occi::StatelessConnectionPool::PoolType) () from /usr/lib/oracle/12.1/client64/lib/libocci.so.12.1
#6  0x00007ffff7b356c1 in oracle::occi::EnvironmentImpl::createStatelessConnectionPool(std::string const&, std::string const&, std::string const&, unsigned int, unsigned int, unsigned int, oracle::occi::StatelessConnectionPool::PoolType) () from /usr/lib/oracle/12.1/client64/lib/libocci.so.12.1

I could avoid the error for a while by using gcc 4.9 instead of 5.
Maybe this helps a bit.
